import {StyleSheet} from 'react-native';
import {Colors} from '../../styles/AppStyles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    backgroundColor: Colors.blankBackground,
  },
  header: {
    flex: 1.1,
    flexDirection: 'column',
    width: '100%',
    padding: 10,
    backgroundColor: Colors.primaryOrange,
  },
  stepBarContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    margin: 2,
    gap: 10,
  },
  stepBar: {
    width: 80,
    height: 5,
    backgroundColor: Colors.cardBackground,
    borderRadius: 10,
  },
  title: {
    position: 'relative',
    top: 55,
    textAlign: 'left',
    fontWeight: '900',
    fontSize: 28,
    color: Colors.textLight,
    marginBottom: 5,
  },
  subtitle: {
    position: 'relative',
    top: 55,
    fontSize: 16,
    textAlign: 'left',
    fontWeight: '600',
    justifyContent: 'center',
    alignItems: 'center',
    textAlignVertical: 'bottom',
    color: Colors.textLight,
    marginBottom: 60,
  },
  body: {
    flex: 9,
    paddingVertical: 20,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  main: {
    textAlign: 'center',
    fontWeight: '900',
    fontSize: 28,
    color: Colors.primaryOrange,
    marginBottom: 10,
  },
  mainText: {
    padding: 10,
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 15,
    color: Colors.textDark,
    marginTop: 10,
  },
  field: {
    marginBottom: 0,
  },
  inputContainer: {
    margin: 5,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: '#D9D9D9',
    borderWidth: 2,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 5,
    gap: 5,
  },
  buttonContainer: {
    margin: 5,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 5,
    gap: 5,
  },
  icon: {
    marginRight: 10,
  },
  p: {
    textAlign: 'center',
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  fieldsets: {
    flex: 7,
    width: '100%',
    justifyContent: 'center',
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  pPassword: {
    position: 'relative',
    textAlign: 'left',
    padding: 5,
    textDecorationLine: 'underline',
    right: -100,
    bottom: 6,
  },
  link: {
    padding: 9,
    color: Colors.primaryOrange,
    fontSize: 16,
    fontWeight: '700',
  },
  pAuth: {
    paddingVertical: 10,
    fontSize: 14,
    textAlign: 'center',
  },
  row: {
    padding: 10,
    flexDirection: 'row',
    gap: 25,
    alignItems: 'center',
  },
  power: {
    color: Colors.primaryOrange,
    fontWeight: '700',
  },
  rowAuth: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
});

export default styles;
