import { StyleSheet } from 'react-native';
import { COLORS } from './ProfileColors';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.WHITE },
  card: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 18,
    margin: 16,
    padding: 18,
    shadowColor: COLORS.ORANGE,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.13,
    shadowRadius: 8,
    elevation: 4,
  },
  avatar: {
    width: 110,
    height: 110,
    borderRadius: 55,
    alignSelf: 'center',
    marginBottom: 8,
    borderWidth: 3,
    borderColor: COLORS.ORANGE,
    backgroundColor: COLORS.LIGHT_ORANGE,
  },
  editPhoto: {
    color: COLORS.ORANGE,
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 8,
    textDecorationLine: 'underline',
  },
  name: { fontSize: 22, fontWeight: 'bold', color: COLORS.ORANGE, textAlign: 'center' },
  email: { color: COLORS.GRAY, marginBottom: 10, textAlign: 'center' },
  input: {
    borderWidth: 1,
    borderColor: COLORS.ORANGE,
    borderRadius: 8,
    padding: 8,
    marginBottom: 10,
    backgroundColor: COLORS.LIGHT_GRAY,
    color: '#222',
    fontSize: 15,
  },
  editBtn: {
    marginTop: 6,
    backgroundColor: COLORS.ORANGE,
    paddingVertical: 7,
    paddingHorizontal: 18,
    borderRadius: 8,
    alignSelf: 'center',
  },
  editBtnText: { color: COLORS.WHITE, fontWeight: 'bold' },
  saveBtn: {
    marginTop: 6,
    backgroundColor: '#ffb74d',
    paddingVertical: 7,
    paddingHorizontal: 18,
    borderRadius: 8,
    alignSelf: 'center',
  },
  saveBtnText: { color: COLORS.ORANGE, fontWeight: 'bold' },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitle: {
    fontWeight: 'bold',
    fontSize: 17,
    color: COLORS.ORANGE,
    marginBottom: 8,
  },
  addBtn: {
    backgroundColor: COLORS.ORANGE,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  addBtnText: { color: COLORS.WHITE, fontWeight: 'bold', fontSize: 15 },
  historyItem: {
    backgroundColor: COLORS.LIGHT_ORANGE,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  historyAction: { color: '#222', fontWeight: 'bold', fontSize: 15 },
  historyDate: { color: COLORS.GRAY, fontSize: 12, marginTop: 2 },
  empty: { color: COLORS.GRAY, fontStyle: 'italic', textAlign: 'center', marginTop: 8 },
  familyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: COLORS.LIGHT_ORANGE,
    borderRadius: 8,
    padding: 8,
  },
  familyItem: { color: '#222', fontSize: 15, flex: 1 },
  deleteBtn: {
    backgroundColor: '#fff3e0',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: COLORS.ORANGE,
  },
  deleteBtnText: { color: COLORS.ORANGE, fontWeight: 'bold' },
  familyAddRow: { flexDirection: 'row', marginTop: 10, alignItems: 'center' },
  preferenceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 8,
  },
  preferenceLabel: { color: '#222', fontSize: 15 },
  switch: {
    width: 50,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#ccc',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.ORANGE,
  },
  switchOn: { backgroundColor: COLORS.ORANGE },
  switchOff: { backgroundColor: '#ccc' },
  switchThumb: (on) => ({
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: COLORS.WHITE,
    marginLeft: on ? 22 : 2,
    elevation: 2,
  }),
  bugBtn: {
    backgroundColor: COLORS.ORANGE,
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 5,
  },
  bugBtnText: { color: COLORS.WHITE, fontWeight: 'bold' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.WHITE },
});

export default styles;